import type { AdminEntityConfig, AdminEntityType } from "@/features/admin/types";
import { provisionalTechnicalMetadata, trainingExerciseMetadata } from "@/features/technical/defaults";

export const adminEntityConfigs: Record<AdminEntityType, AdminEntityConfig> = {
  course: {
    type: "course",
    collectionName: "courses",
    label: "Curso",
    pluralLabel: "Cursos",
    description: "Gerencie cursos, publicação, pré-requisitos e metadados principais.",
    titleField: "title",
    slugField: "slug",
    searchFields: ["title", "description", "category", "level", "slug"],
    relationFields: ["prerequisites", "nextCourseId"],
    technical: false,
    uploadFolder: "courseImages",
    defaultValues: {
      title: "",
      slug: "",
      description: "",
      category: "Fundamentos da Pilotagem",
      level: "Inicial",
      estimatedDuration: "",
      imageIcon: "Plane",
      audience: "Aluno de simulador",
      referenceAircraft: "",
      language: "pt-BR",
      disclaimer: "Conteúdo destinado a estudos em simulador. Não substitui documentos oficiais ou instrução real.",
      prerequisites: [],
      nextCourseId: "",
      order: 999,
      progressPercent: 0,
      moduleCount: 0,
      status: "not_started",
      publicationState: "draft"
    }
  },
  module: {
    type: "module",
    collectionName: "modules",
    label: "Módulo",
    pluralLabel: "Módulos",
    description: "Organize módulos por curso, ordem, duração e pré-requisitos.",
    titleField: "title",
    searchFields: ["title", "description", "courseId"],
    relationFields: ["courseId", "prerequisites"],
    technical: false,
    defaultValues: {
      courseId: "",
      title: "",
      description: "",
      order: 999,
      lessonIds: [],
      duration: "",
      status: "not_started",
      progressPercent: 0,
      prerequisites: [],
      publicationState: "draft"
    }
  },
  lesson: {
    type: "lesson",
    collectionName: "lessons",
    label: "Aula",
    pluralLabel: "Aulas",
    description: "Edite aulas em Markdown ou blocos simples, com objetivo e avisos técnicos.",
    titleField: "title",
    slugField: "slug",
    searchFields: ["title", "summary", "objective", "slug", "moduleId"],
    relationFields: ["moduleId", "previousLessonId", "nextLessonId", "exerciseId"],
    technical: true,
    uploadFolder: "lessonImages",
    defaultValues: {
      moduleId: "",
      title: "",
      slug: "",
      summary: "",
      introduction: "",
      didacticExplanation: "",
      example: "",
      commonMistake: "",
      simulatorApplication: "",
      exercisePrompt: "",
      expectedAnswer: "",
      conclusion: "",
      nextLessonConnection: "",
      previousLessonId: "",
      nextLessonId: "",
      content: [],
      order: 999,
      estimatedDuration: "",
      objective: "",
      keyConcepts: [],
      exerciseId: "",
      exerciseIds: [],
      status: "locked",
      actions: {
        canComplete: true,
        canContinue: true,
        canGoBack: true
      },
      publicationState: "draft",
      technicalMetadata: provisionalTechnicalMetadata({ contentClassification: "educational_explanation" })
    }
  },
  exercise: {
    type: "exercise",
    collectionName: "exercises",
    label: "Exercício",
    pluralLabel: "Exercícios",
    description: "Configure múltipla escolha, verdadeiro/falso e resposta aberta.",
    titleField: "prompt",
    searchFields: ["prompt", "expectedAnswer", "lessonId", "courseId", "moduleId"],
    relationFields: ["courseId", "moduleId", "lessonId"],
    technical: false,
    defaultValues: {
      lessonId: "",
      moduleId: "",
      courseId: "",
      type: "multiple_choice",
      prompt: "",
      alternatives: ["Alternativa A", "Alternativa B"],
      alternativeOptions: [
        { id: "option-a", text: "Alternativa A" },
        { id: "option-b", text: "Alternativa B" }
      ],
      correctAnswer: "option-a",
      expectedAnswer: "",
      explanation: "",
      difficulty: "facil",
      order: 999,
      points: 1,
      publicationState: "draft",
      technicalMetadata: trainingExerciseMetadata()
    }
  },
  aircraft: {
    type: "aircraft",
    collectionName: "aircraft",
    label: "Aeronave",
    pluralLabel: "Aeronaves",
    description: "Cadastre aeronaves, variantes, sistemas, relações e imagens.",
    titleField: "fullName",
    slugField: "slug",
    searchFields: ["fullName", "manufacturer", "model", "category", "slug"],
    relationFields: ["relatedCourseIds", "installedAvionicIds", "checklistIds", "trainingIds"],
    technical: true,
    uploadFolder: "aircraftImages",
    defaultValues: {
      slug: "",
      manufacturer: "",
      model: "",
      fullName: "",
      category: "",
      engineType: "",
      numberOfEngines: null,
      cruiseSpeed: "",
      range: "",
      serviceCeiling: "",
      capacity: "",
      description: "",
      mainImage: {
        id: "",
        aircraftId: "",
        kind: "main",
        alt: "",
        publicationState: "draft",
        createdAt: "",
        updatedAt: ""
      },
      gallery: [],
      studyStatus: "planned",
      progressPercent: 0,
      systemIds: [],
      limitationIds: [],
      procedureIds: [],
      performanceIds: [],
      checklistIds: [],
      trainingIds: [],
      relatedCourseIds: [],
      installedAvionicIds: [],
      publicationState: "draft",
      technicalMetadata: provisionalTechnicalMetadata()
    }
  },
  avionic: {
    type: "avionic",
    collectionName: "avionics",
    label: "Aviônico",
    pluralLabel: "Aviônicos",
    description: "Gerencie aviônicos, seções, relações e diferenças no simulador.",
    titleField: "name",
    slugField: "slug",
    searchFields: ["name", "manufacturer", "version", "description", "slug"],
    relationFields: ["compatibleAircraftIds", "courseIds", "trainingIds"],
    technical: true,
    uploadFolder: "avionicsImages",
    defaultValues: {
      slug: "",
      name: "",
      manufacturer: "",
      version: "",
      description: "",
      image: {
        id: "",
        avionicId: "",
        kind: "main",
        alt: "",
        publicationState: "draft",
        createdAt: "",
        updatedAt: ""
      },
      compatibleAircraftIds: [],
      courseIds: [],
      componentIds: [],
      procedureIds: [],
      trainingIds: [],
      progressPercent: 0,
      studyStatus: "planned",
      publicationState: "draft",
      technicalMetadata: provisionalTechnicalMetadata()
    }
  },
  checklist: {
    type: "checklist",
    collectionName: "checklists",
    label: "Checklist",
    pluralLabel: "Checklists",
    description: "Controle fases do voo, itens, versões, fonte e publicação.",
    titleField: "title",
    slugField: "slug",
    searchFields: ["title", "description", "aircraftName", "flightPhase", "slug"],
    relationFields: ["aircraftId"],
    technical: true,
    defaultValues: {
      slug: "",
      aircraftId: "",
      aircraftName: "",
      flightPhase: "preparacao",
      title: "",
      description: "",
      items: [],
      order: 999,
      notes: "",
      version: "0.1",
      studyMode: { enabled: true, description: "Modo de estudo com explicações e observações." },
      operationalMode: { enabled: true, description: "Modo simplificado para simulação no iPad." },
      publicationState: "draft",
      technicalMetadata: provisionalTechnicalMetadata()
    }
  },
  training: {
    type: "training",
    collectionName: "trainings",
    label: "Treinamento",
    pluralLabel: "Treinamentos",
    description: "Monte missões práticas de simulador com critérios de conclusão.",
    titleField: "title",
    slugField: "slug",
    searchFields: ["title", "aircraftName", "objective", "difficulty", "slug"],
    relationFields: ["aircraftId", "relatedCourseId", "relatedLessonId"],
    technical: true,
    defaultValues: {
      slug: "",
      title: "",
      aircraftId: "",
      aircraftName: "",
      difficulty: "Inicial",
      duration: "",
      departureAirport: "",
      destinationAirport: "",
      conditions: "",
      objective: "",
      instructions: [],
      completionCriteria: [],
      studentReport: "",
      personalNote: "",
      status: "not_started",
      relatedCourseId: "",
      relatedCourseSlug: "",
      relatedLessonId: "",
      relatedLessonSlug: "",
      publicationState: "draft",
      technicalMetadata: trainingExerciseMetadata()
    }
  }
};

export const adminEntityOrder: AdminEntityType[] = ["course", "module", "lesson", "exercise", "aircraft", "avionic", "checklist", "training"];
